export interface CountryCode {
  code: string;   // ISO 3166-1 alpha-2
  name: string;
  dial: string;   // e.g. "+20"
  flag: string;   // emoji flag
  minDigits: number; // min local digits (after dial code)
  maxDigits: number; // max local digits
}

export const COUNTRY_CODES: CountryCode[] = [
  { code: "AF", name: "Afghanistan", dial: "+93", flag: "\u{1F1E6}\u{1F1EB}", minDigits: 9, maxDigits: 9 },
  { code: "AL", name: "Albania", dial: "+355", flag: "\u{1F1E6}\u{1F1F1}", minDigits: 8, maxDigits: 9 },
  { code: "DZ", name: "Algeria", dial: "+213", flag: "\u{1F1E9}\u{1F1FF}", minDigits: 8, maxDigits: 9 },
  { code: "AR", name: "Argentina", dial: "+54", flag: "\u{1F1E6}\u{1F1F7}", minDigits: 10, maxDigits: 11 },
  { code: "AM", name: "Armenia", dial: "+374", flag: "\u{1F1E6}\u{1F1F2}", minDigits: 8, maxDigits: 8 },
  { code: "AU", name: "Australia", dial: "+61", flag: "\u{1F1E6}\u{1F1FA}", minDigits: 9, maxDigits: 9 },
  { code: "AT", name: "Austria", dial: "+43", flag: "\u{1F1E6}\u{1F1F9}", minDigits: 7, maxDigits: 13 },
  { code: "AZ", name: "Azerbaijan", dial: "+994", flag: "\u{1F1E6}\u{1F1FF}", minDigits: 9, maxDigits: 9 },
  { code: "BH", name: "Bahrain", dial: "+973", flag: "\u{1F1E7}\u{1F1ED}", minDigits: 8, maxDigits: 8 },
  { code: "BD", name: "Bangladesh", dial: "+880", flag: "\u{1F1E7}\u{1F1E9}", minDigits: 10, maxDigits: 10 },
  { code: "BY", name: "Belarus", dial: "+375", flag: "\u{1F1E7}\u{1F1FE}", minDigits: 9, maxDigits: 10 },
  { code: "BE", name: "Belgium", dial: "+32", flag: "\u{1F1E7}\u{1F1EA}", minDigits: 8, maxDigits: 9 },
  { code: "BJ", name: "Benin", dial: "+229", flag: "\u{1F1E7}\u{1F1EF}", minDigits: 8, maxDigits: 8 },
  { code: "BO", name: "Bolivia", dial: "+591", flag: "\u{1F1E7}\u{1F1F4}", minDigits: 8, maxDigits: 8 },
  { code: "BA", name: "Bosnia and Herzegovina", dial: "+387", flag: "\u{1F1E7}\u{1F1E6}", minDigits: 8, maxDigits: 8 },
  { code: "BW", name: "Botswana", dial: "+267", flag: "\u{1F1E7}\u{1F1FC}", minDigits: 7, maxDigits: 8 },
  { code: "BR", name: "Brazil", dial: "+55", flag: "\u{1F1E7}\u{1F1F7}", minDigits: 10, maxDigits: 11 },
  { code: "BN", name: "Brunei", dial: "+673", flag: "\u{1F1E7}\u{1F1F3}", minDigits: 7, maxDigits: 7 },
  { code: "BG", name: "Bulgaria", dial: "+359", flag: "\u{1F1E7}\u{1F1EC}", minDigits: 8, maxDigits: 9 },
  { code: "BF", name: "Burkina Faso", dial: "+226", flag: "\u{1F1E7}\u{1F1EB}", minDigits: 8, maxDigits: 8 },
  { code: "KH", name: "Cambodia", dial: "+855", flag: "\u{1F1F0}\u{1F1ED}", minDigits: 8, maxDigits: 9 },
  { code: "CM", name: "Cameroon", dial: "+237", flag: "\u{1F1E8}\u{1F1F2}", minDigits: 8, maxDigits: 9 },
  { code: "CA", name: "Canada", dial: "+1", flag: "\u{1F1E8}\u{1F1E6}", minDigits: 10, maxDigits: 10 },
  { code: "CL", name: "Chile", dial: "+56", flag: "\u{1F1E8}\u{1F1F1}", minDigits: 9, maxDigits: 9 },
  { code: "CN", name: "China", dial: "+86", flag: "\u{1F1E8}\u{1F1F3}", minDigits: 11, maxDigits: 11 },
  { code: "CO", name: "Colombia", dial: "+57", flag: "\u{1F1E8}\u{1F1F4}", minDigits: 10, maxDigits: 10 },
  { code: "CD", name: "Congo (DRC)", dial: "+243", flag: "\u{1F1E8}\u{1F1E9}", minDigits: 9, maxDigits: 9 },
  { code: "CR", name: "Costa Rica", dial: "+506", flag: "\u{1F1E8}\u{1F1F7}", minDigits: 8, maxDigits: 8 },
  { code: "CI", name: "C\u00f4te d'Ivoire", dial: "+225", flag: "\u{1F1E8}\u{1F1EE}", minDigits: 10, maxDigits: 10 },
  { code: "HR", name: "Croatia", dial: "+385", flag: "\u{1F1ED}\u{1F1F7}", minDigits: 8, maxDigits: 9 },
  { code: "CU", name: "Cuba", dial: "+53", flag: "\u{1F1E8}\u{1F1FA}", minDigits: 8, maxDigits: 8 },
  { code: "CY", name: "Cyprus", dial: "+357", flag: "\u{1F1E8}\u{1F1FE}", minDigits: 8, maxDigits: 8 },
  { code: "CZ", name: "Czech Republic", dial: "+420", flag: "\u{1F1E8}\u{1F1FF}", minDigits: 9, maxDigits: 9 },
  { code: "DK", name: "Denmark", dial: "+45", flag: "\u{1F1E9}\u{1F1F0}", minDigits: 8, maxDigits: 8 },
  { code: "DJ", name: "Djibouti", dial: "+253", flag: "\u{1F1E9}\u{1F1EF}", minDigits: 8, maxDigits: 8 },
  { code: "DO", name: "Dominican Republic", dial: "+1", flag: "\u{1F1E9}\u{1F1F4}", minDigits: 10, maxDigits: 10 },
  { code: "EC", name: "Ecuador", dial: "+593", flag: "\u{1F1EA}\u{1F1E8}", minDigits: 9, maxDigits: 9 },
  { code: "EG", name: "Egypt", dial: "+20", flag: "\u{1F1EA}\u{1F1EC}", minDigits: 10, maxDigits: 10 },
  { code: "SV", name: "El Salvador", dial: "+503", flag: "\u{1F1F8}\u{1F1FB}", minDigits: 8, maxDigits: 8 },
  { code: "EE", name: "Estonia", dial: "+372", flag: "\u{1F1EA}\u{1F1EA}", minDigits: 7, maxDigits: 8 },
  { code: "ET", name: "Ethiopia", dial: "+251", flag: "\u{1F1EA}\u{1F1F9}", minDigits: 9, maxDigits: 9 },
  { code: "FI", name: "Finland", dial: "+358", flag: "\u{1F1EB}\u{1F1EE}", minDigits: 7, maxDigits: 10 },
  { code: "FR", name: "France", dial: "+33", flag: "\u{1F1EB}\u{1F1F7}", minDigits: 9, maxDigits: 9 },
  { code: "GA", name: "Gabon", dial: "+241", flag: "\u{1F1EC}\u{1F1E6}", minDigits: 7, maxDigits: 8 },
  { code: "GE", name: "Georgia", dial: "+995", flag: "\u{1F1EC}\u{1F1EA}", minDigits: 9, maxDigits: 9 },
  { code: "DE", name: "Germany", dial: "+49", flag: "\u{1F1E9}\u{1F1EA}", minDigits: 7, maxDigits: 12 },
  { code: "GH", name: "Ghana", dial: "+233", flag: "\u{1F1EC}\u{1F1ED}", minDigits: 9, maxDigits: 9 },
  { code: "GR", name: "Greece", dial: "+30", flag: "\u{1F1EC}\u{1F1F7}", minDigits: 10, maxDigits: 10 },
  { code: "GT", name: "Guatemala", dial: "+502", flag: "\u{1F1EC}\u{1F1F9}", minDigits: 8, maxDigits: 8 },
  { code: "GN", name: "Guinea", dial: "+224", flag: "\u{1F1EC}\u{1F1F3}", minDigits: 8, maxDigits: 9 },
  { code: "HN", name: "Honduras", dial: "+504", flag: "\u{1F1ED}\u{1F1F3}", minDigits: 8, maxDigits: 8 },
  { code: "HK", name: "Hong Kong", dial: "+852", flag: "\u{1F1ED}\u{1F1F0}", minDigits: 8, maxDigits: 8 },
  { code: "HU", name: "Hungary", dial: "+36", flag: "\u{1F1ED}\u{1F1FA}", minDigits: 8, maxDigits: 9 },
  { code: "IS", name: "Iceland", dial: "+354", flag: "\u{1F1EE}\u{1F1F8}", minDigits: 7, maxDigits: 7 },
  { code: "IN", name: "India", dial: "+91", flag: "\u{1F1EE}\u{1F1F3}", minDigits: 10, maxDigits: 10 },
  { code: "ID", name: "Indonesia", dial: "+62", flag: "\u{1F1EE}\u{1F1E9}", minDigits: 9, maxDigits: 12 },
  { code: "IR", name: "Iran", dial: "+98", flag: "\u{1F1EE}\u{1F1F7}", minDigits: 10, maxDigits: 10 },
  { code: "IQ", name: "Iraq", dial: "+964", flag: "\u{1F1EE}\u{1F1F6}", minDigits: 10, maxDigits: 10 },
  { code: "IE", name: "Ireland", dial: "+353", flag: "\u{1F1EE}\u{1F1EA}", minDigits: 7, maxDigits: 9 },
  { code: "IL", name: "Israel", dial: "+972", flag: "\u{1F1EE}\u{1F1F1}", minDigits: 9, maxDigits: 9 },
  { code: "IT", name: "Italy", dial: "+39", flag: "\u{1F1EE}\u{1F1F9}", minDigits: 9, maxDigits: 10 },
  { code: "JM", name: "Jamaica", dial: "+1", flag: "\u{1F1EF}\u{1F1F2}", minDigits: 10, maxDigits: 10 },
  { code: "JP", name: "Japan", dial: "+81", flag: "\u{1F1EF}\u{1F1F5}", minDigits: 10, maxDigits: 10 },
  { code: "JO", name: "Jordan", dial: "+962", flag: "\u{1F1EF}\u{1F1F4}", minDigits: 9, maxDigits: 9 },
  { code: "KZ", name: "Kazakhstan", dial: "+7", flag: "\u{1F1F0}\u{1F1FF}", minDigits: 10, maxDigits: 10 },
  { code: "KE", name: "Kenya", dial: "+254", flag: "\u{1F1F0}\u{1F1EA}", minDigits: 9, maxDigits: 10 },
  { code: "KW", name: "Kuwait", dial: "+965", flag: "\u{1F1F0}\u{1F1FC}", minDigits: 8, maxDigits: 8 },
  { code: "KG", name: "Kyrgyzstan", dial: "+996", flag: "\u{1F1F0}\u{1F1EC}", minDigits: 9, maxDigits: 9 },
  { code: "LA", name: "Laos", dial: "+856", flag: "\u{1F1F1}\u{1F1E6}", minDigits: 8, maxDigits: 10 },
  { code: "LV", name: "Latvia", dial: "+371", flag: "\u{1F1F1}\u{1F1FB}", minDigits: 8, maxDigits: 8 },
  { code: "LB", name: "Lebanon", dial: "+961", flag: "\u{1F1F1}\u{1F1E7}", minDigits: 7, maxDigits: 8 },
  { code: "LY", name: "Libya", dial: "+218", flag: "\u{1F1F1}\u{1F1FE}", minDigits: 9, maxDigits: 10 },
  { code: "LT", name: "Lithuania", dial: "+370", flag: "\u{1F1F1}\u{1F1F9}", minDigits: 8, maxDigits: 8 },
  { code: "LU", name: "Luxembourg", dial: "+352", flag: "\u{1F1F1}\u{1F1FA}", minDigits: 6, maxDigits: 9 },
  { code: "MG", name: "Madagascar", dial: "+261", flag: "\u{1F1F2}\u{1F1EC}", minDigits: 9, maxDigits: 9 },
  { code: "MY", name: "Malaysia", dial: "+60", flag: "\u{1F1F2}\u{1F1FE}", minDigits: 9, maxDigits: 10 },
  { code: "ML", name: "Mali", dial: "+223", flag: "\u{1F1F2}\u{1F1F1}", minDigits: 8, maxDigits: 8 },
  { code: "MT", name: "Malta", dial: "+356", flag: "\u{1F1F2}\u{1F1F9}", minDigits: 8, maxDigits: 8 },
  { code: "MR", name: "Mauritania", dial: "+222", flag: "\u{1F1F2}\u{1F1F7}", minDigits: 8, maxDigits: 8 },
  { code: "MU", name: "Mauritius", dial: "+230", flag: "\u{1F1F2}\u{1F1FA}", minDigits: 7, maxDigits: 8 },
  { code: "MX", name: "Mexico", dial: "+52", flag: "\u{1F1F2}\u{1F1FD}", minDigits: 10, maxDigits: 10 },
  { code: "MD", name: "Moldova", dial: "+373", flag: "\u{1F1F2}\u{1F1E9}", minDigits: 8, maxDigits: 8 },
  { code: "MN", name: "Mongolia", dial: "+976", flag: "\u{1F1F2}\u{1F1F3}", minDigits: 8, maxDigits: 8 },
  { code: "ME", name: "Montenegro", dial: "+382", flag: "\u{1F1F2}\u{1F1EA}", minDigits: 8, maxDigits: 8 },
  { code: "MA", name: "Morocco", dial: "+212", flag: "\u{1F1F2}\u{1F1E6}", minDigits: 9, maxDigits: 9 },
  { code: "MZ", name: "Mozambique", dial: "+258", flag: "\u{1F1F2}\u{1F1FF}", minDigits: 9, maxDigits: 9 },
  { code: "MM", name: "Myanmar", dial: "+95", flag: "\u{1F1F2}\u{1F1F2}", minDigits: 8, maxDigits: 10 },
  { code: "NA", name: "Namibia", dial: "+264", flag: "\u{1F1F3}\u{1F1E6}", minDigits: 7, maxDigits: 9 },
  { code: "NP", name: "Nepal", dial: "+977", flag: "\u{1F1F3}\u{1F1F5}", minDigits: 10, maxDigits: 10 },
  { code: "NL", name: "Netherlands", dial: "+31", flag: "\u{1F1F3}\u{1F1F1}", minDigits: 9, maxDigits: 9 },
  { code: "NZ", name: "New Zealand", dial: "+64", flag: "\u{1F1F3}\u{1F1FF}", minDigits: 8, maxDigits: 10 },
  { code: "NI", name: "Nicaragua", dial: "+505", flag: "\u{1F1F3}\u{1F1EE}", minDigits: 8, maxDigits: 8 },
  { code: "NE", name: "Niger", dial: "+227", flag: "\u{1F1F3}\u{1F1EA}", minDigits: 8, maxDigits: 8 },
  { code: "NG", name: "Nigeria", dial: "+234", flag: "\u{1F1F3}\u{1F1EC}", minDigits: 10, maxDigits: 10 },
  { code: "MK", name: "North Macedonia", dial: "+389", flag: "\u{1F1F2}\u{1F1F0}", minDigits: 8, maxDigits: 8 },
  { code: "NO", name: "Norway", dial: "+47", flag: "\u{1F1F3}\u{1F1F4}", minDigits: 8, maxDigits: 8 },
  { code: "OM", name: "Oman", dial: "+968", flag: "\u{1F1F4}\u{1F1F2}", minDigits: 8, maxDigits: 8 },
  { code: "PK", name: "Pakistan", dial: "+92", flag: "\u{1F1F5}\u{1F1F0}", minDigits: 10, maxDigits: 10 },
  { code: "PS", name: "Palestine", dial: "+970", flag: "\u{1F1F5}\u{1F1F8}", minDigits: 9, maxDigits: 9 },
  { code: "PA", name: "Panama", dial: "+507", flag: "\u{1F1F5}\u{1F1E6}", minDigits: 7, maxDigits: 8 },
  { code: "PY", name: "Paraguay", dial: "+595", flag: "\u{1F1F5}\u{1F1FE}", minDigits: 9, maxDigits: 9 },
  { code: "PE", name: "Peru", dial: "+51", flag: "\u{1F1F5}\u{1F1EA}", minDigits: 9, maxDigits: 9 },
  { code: "PH", name: "Philippines", dial: "+63", flag: "\u{1F1F5}\u{1F1ED}", minDigits: 10, maxDigits: 10 },
  { code: "PL", name: "Poland", dial: "+48", flag: "\u{1F1F5}\u{1F1F1}", minDigits: 9, maxDigits: 9 },
  { code: "PT", name: "Portugal", dial: "+351", flag: "\u{1F1F5}\u{1F1F9}", minDigits: 9, maxDigits: 9 },
  { code: "QA", name: "Qatar", dial: "+974", flag: "\u{1F1F6}\u{1F1E6}", minDigits: 8, maxDigits: 8 },
  { code: "RO", name: "Romania", dial: "+40", flag: "\u{1F1F7}\u{1F1F4}", minDigits: 9, maxDigits: 9 },
  { code: "RU", name: "Russia", dial: "+7", flag: "\u{1F1F7}\u{1F1FA}", minDigits: 10, maxDigits: 10 },
  { code: "RW", name: "Rwanda", dial: "+250", flag: "\u{1F1F7}\u{1F1FC}", minDigits: 9, maxDigits: 9 },
  { code: "SA", name: "Saudi Arabia", dial: "+966", flag: "\u{1F1F8}\u{1F1E6}", minDigits: 9, maxDigits: 9 },
  { code: "SN", name: "Senegal", dial: "+221", flag: "\u{1F1F8}\u{1F1F3}", minDigits: 9, maxDigits: 9 },
  { code: "RS", name: "Serbia", dial: "+381", flag: "\u{1F1F7}\u{1F1F8}", minDigits: 8, maxDigits: 9 },
  { code: "SG", name: "Singapore", dial: "+65", flag: "\u{1F1F8}\u{1F1EC}", minDigits: 8, maxDigits: 8 },
  { code: "SK", name: "Slovakia", dial: "+421", flag: "\u{1F1F8}\u{1F1F0}", minDigits: 9, maxDigits: 9 },
  { code: "SI", name: "Slovenia", dial: "+386", flag: "\u{1F1F8}\u{1F1EE}", minDigits: 8, maxDigits: 8 },
  { code: "SO", name: "Somalia", dial: "+252", flag: "\u{1F1F8}\u{1F1F4}", minDigits: 7, maxDigits: 8 },
  { code: "ZA", name: "South Africa", dial: "+27", flag: "\u{1F1FF}\u{1F1E6}", minDigits: 9, maxDigits: 9 },
  { code: "KR", name: "South Korea", dial: "+82", flag: "\u{1F1F0}\u{1F1F7}", minDigits: 9, maxDigits: 10 },
  { code: "SS", name: "South Sudan", dial: "+211", flag: "\u{1F1F8}\u{1F1F8}", minDigits: 9, maxDigits: 9 },
  { code: "ES", name: "Spain", dial: "+34", flag: "\u{1F1EA}\u{1F1F8}", minDigits: 9, maxDigits: 9 },
  { code: "LK", name: "Sri Lanka", dial: "+94", flag: "\u{1F1F1}\u{1F1F0}", minDigits: 9, maxDigits: 9 },
  { code: "SD", name: "Sudan", dial: "+249", flag: "\u{1F1F8}\u{1F1E9}", minDigits: 9, maxDigits: 9 },
  { code: "SE", name: "Sweden", dial: "+46", flag: "\u{1F1F8}\u{1F1EA}", minDigits: 7, maxDigits: 10 },
  { code: "CH", name: "Switzerland", dial: "+41", flag: "\u{1F1E8}\u{1F1ED}", minDigits: 9, maxDigits: 9 },
  { code: "SY", name: "Syria", dial: "+963", flag: "\u{1F1F8}\u{1F1FE}", minDigits: 9, maxDigits: 9 },
  { code: "TW", name: "Taiwan", dial: "+886", flag: "\u{1F1F9}\u{1F1FC}", minDigits: 9, maxDigits: 9 },
  { code: "TZ", name: "Tanzania", dial: "+255", flag: "\u{1F1F9}\u{1F1FF}", minDigits: 9, maxDigits: 9 },
  { code: "TH", name: "Thailand", dial: "+66", flag: "\u{1F1F9}\u{1F1ED}", minDigits: 9, maxDigits: 9 },
  { code: "TN", name: "Tunisia", dial: "+216", flag: "\u{1F1F9}\u{1F1F3}", minDigits: 8, maxDigits: 8 },
  { code: "TR", name: "Turkey", dial: "+90", flag: "\u{1F1F9}\u{1F1F7}", minDigits: 10, maxDigits: 10 },
  { code: "TM", name: "Turkmenistan", dial: "+993", flag: "\u{1F1F9}\u{1F1F2}", minDigits: 8, maxDigits: 8 },
  { code: "UG", name: "Uganda", dial: "+256", flag: "\u{1F1FA}\u{1F1EC}", minDigits: 9, maxDigits: 9 },
  { code: "UA", name: "Ukraine", dial: "+380", flag: "\u{1F1FA}\u{1F1E6}", minDigits: 9, maxDigits: 9 },
  { code: "AE", name: "United Arab Emirates", dial: "+971", flag: "\u{1F1E6}\u{1F1EA}", minDigits: 9, maxDigits: 9 },
  { code: "GB", name: "United Kingdom", dial: "+44", flag: "\u{1F1EC}\u{1F1E7}", minDigits: 10, maxDigits: 10 },
  { code: "US", name: "United States", dial: "+1", flag: "\u{1F1FA}\u{1F1F8}", minDigits: 10, maxDigits: 10 },
  { code: "UY", name: "Uruguay", dial: "+598", flag: "\u{1F1FA}\u{1F1FE}", minDigits: 8, maxDigits: 8 },
  { code: "UZ", name: "Uzbekistan", dial: "+998", flag: "\u{1F1FA}\u{1F1FF}", minDigits: 9, maxDigits: 9 },
  { code: "VE", name: "Venezuela", dial: "+58", flag: "\u{1F1FB}\u{1F1EA}", minDigits: 10, maxDigits: 10 },
  { code: "VN", name: "Vietnam", dial: "+84", flag: "\u{1F1FB}\u{1F1F3}", minDigits: 9, maxDigits: 10 },
  { code: "YE", name: "Yemen", dial: "+967", flag: "\u{1F1FE}\u{1F1EA}", minDigits: 9, maxDigits: 9 },
  { code: "ZM", name: "Zambia", dial: "+260", flag: "\u{1F1FF}\u{1F1F2}", minDigits: 9, maxDigits: 9 },
  { code: "ZW", name: "Zimbabwe", dial: "+263", flag: "\u{1F1FF}\u{1F1FC}", minDigits: 9, maxDigits: 9 },
];

export function findCountryByCode(code: string): CountryCode | undefined {
  return COUNTRY_CODES.find((c) => c.code === code);
}

export function findCountryByDial(dial: string): CountryCode | undefined {
  return COUNTRY_CODES.find((c) => c.dial === dial);
}

export function validatePhone(digits: string, country: CountryCode): boolean {
  const cleaned = digits.replace(/\D/g, "");
  return cleaned.length >= country.minDigits && cleaned.length <= country.maxDigits;
}
