export type Project = {
  slug: string;
  title: string;
  category: string;
  client: string;
  year: string;
  description: string;
  preview: string;
  previewMobile?: string;
  url: string;
  noEmbed?: boolean;
  problemHeading: string;
  problemBody: string;
  solutionHeading: string;
  solutionBody: string;
  image1: string;
  image2: string;
  gallery: string[];
  results?: { metric: string; detail: string }[];
  journey?: { step: string; date: string; body: string }[];
};

export const PROJECTS: Project[] = [
  {
    slug: "alfa-transport",
    title: "Alfa Transport",
    category: "Website Development",
    client: "Alfa Transport",
    year: "2026",
    url: "https://www.alfatransport.sa",
    description: "Alfa Transport had 17+ years of experience and 10,000+ safe shipments but no website at all. VELIQ built their digital presence from scratch with SEO built in from day one.",
    preview: "/uploads/alfa-transport-screen.webp",
    problemHeading: "Alfa Transport had the track record. They didn't have a website.",
    problemBody: "With 17+ years in road transport and logistics, 10,000+ safe shipments, and a fleet of 200+ modern transport equipment, Alfa Transport had no digital presence at all. There was no way for partners, contractors, or clients across the construction and logistics sectors to find them online, learn about their services, or verify a track record built over nearly two decades.",
    solutionHeading: "We built their entire digital presence, with SEO built in from day one, not bolted on afterward.",
    solutionBody: "VELIQ designed and built the complete Alfa Transport website from scratch: their company profile, their core services (bulk cement distribution, specialized road transport, cargo inspection and safety, and international transport solutions), and their certifications (transport license, ISO accreditations). SEO wasn't a separate phase added later. Technical foundations, structured content, and search-ready pages were built into the site from launch.",
    image1: "/uploads/alfa-transport-1.webp",
    image2: "/uploads/alfa-transport-2.webp",
    gallery: [
      "/uploads/alfa-transport-3.webp",
      "/uploads/alfa-transport-4.webp",
      "/uploads/alfa-transport-5.webp",
    ],
    results: [
      { metric: "4,190+", detail: "Search impressions on Google" },
      { metric: "184", detail: "Organic clicks to the site" },
      { metric: "7.3", detail: "Average search position, near page one" },
    ],
    journey: [
      {
        step: "Discovery",
        date: "Early March 2026",
        body: "We started from zero, no existing website to build on. The journey began with a discovery meeting with Alfa Transport to understand their business, their services, and exactly what the site needed to do for them.",
      },
      {
        step: "Blueprint & Sign-off",
        date: "Early to Mid March 2026",
        body: "We prepared the site's structure and overall direction, then brought it back to Alfa Transport in a dedicated review meeting to confirm everything before moving into execution.",
      },
      {
        step: "Execution, in Lockstep",
        date: "Mid to Late March 2026",
        body: "We built the site phase by phase, in continuous alignment with Alfa Transport throughout. After every phase, we held a review session with them. Nothing moved forward without their green light.",
      },
      {
        step: "Launch",
        date: "End of March 2026",
        body: "The site went live: built around their services and certifications, with SEO foundations already in place, ready to be found from day one, not months later.",
      },
      {
        step: "Ongoing Care",
        date: "End of March 2026 to Present",
        body: "Launch wasn't the finish line. We stayed in the backend, proactively checking that everything kept working, whether they asked us to or not. When they flagged something, we moved on it immediately.",
      },
    ],
  },
  {
    slug: "yamin-estate",
    title: "Yamin Estate",
    category: "Website Development",
    client: "Yamin Estate",
    year: "2025",
    url: "https://www.yamin.estate",
    noEmbed: true,
    description: "An immersive property platform that turned browsers into buyers before they ever visited the showroom.",
    preview: "/uploads/yamin-estate-screen.webp",
    previewMobile: "/uploads/yamin-estate-mobile.webp",
    problemHeading: "A real estate developer was losing qualified buyers to competitors with superior property showcase experiences online.",
    problemBody: "Yamin Estate was launching a premium residential development but their digital presence couldn't convey the quality of the properties. Prospective buyers were visiting competitor sites with immersive virtual tours and 3D renders, and choosing them without ever booking an in-person visit with Yamin.",
    solutionHeading: "We built an immersive property platform that turns browsers into committed buyers before they ever visit a showroom.",
    solutionBody: "We created a premium real estate website with a unit explorer, floor plan viewer, and automated lead qualification flow. The launch campaign generated 450 qualified leads in 30 days, converting 12% to sales consultations, their best launch performance to date.",
    image1: "/uploads/yamin-estate-1.webp",
    image2: "/uploads/yamin-estate-2.webp",
    gallery: [
      "/uploads/yamin-estate-3.webp",
      "/uploads/yamin-estate-4.webp",
      "/uploads/yamin-estate-5.webp",
    ],
    results: [
      { metric: "450", detail: "Qualified leads generated in 30 days" },
      { metric: "12%", detail: "Lead-to-consultation conversion rate" },
      { metric: "#1", detail: "Best launch performance to date" },
    ],
  },
  {
    slug: "saudi-hayat",
    title: "Saudi Hayat",
    category: "Website Development",
    client: "Saudi Hayat",
    year: "2026",
    url: "https://www.saudihayat.com",
    description: "Saudi Hayat had 11+ years of real estate development experience and 20+ completed projects but no website at all. VELIQ built their digital presence from scratch with SEO built in from day one.",
    preview: "/uploads/saudi-hayat-screen.webp",
    problemHeading: "Saudi Hayat had the track record. They didn't have a website.",
    problemBody: "With more than 11 years in the real estate market and 20+ completed developments, including their flagship Haya Tower, Saudi Hayat had no digital presence at all. There was no way for buyers, investors, or partners to find them online, learn about their projects, or verify a decade of credibility. Everything they'd built offline had nowhere to live on the web.",
    solutionHeading: "We built their entire digital presence, with SEO built in from day one, not bolted on afterward.",
    solutionBody: "VELIQ designed and built the complete Saudi Hayat website from scratch: their company story, their four core services (development, property management, marketing, and consulting), and their project portfolio, including the flagship Haya Tower. SEO wasn't a separate phase added later. Technical foundations, structured content, and search-ready pages were built into the site from launch.",
    image1: "/uploads/saudi-hayat-1.webp",
    image2: "/uploads/saudi-hayat-2.webp",
    gallery: [
      "/uploads/saudi-hayat-3.webp",
      "/uploads/saudi-hayat-4.webp",
      "/uploads/saudi-hayat-5.webp",
    ],
    results: [
      { metric: "1,540+", detail: "Search impressions on Google" },
      { metric: "65", detail: "Organic clicks to the site" },
      { metric: "19.2", detail: "Average search position, and climbing" },
    ],
    journey: [
      {
        step: "Discovery",
        date: "Early March 2026",
        body: "We started from zero, no existing website to build on. The journey began with a discovery meeting with Saudi Hayat to understand their business, their portfolio, and exactly what the site needed to do for them.",
      },
      {
        step: "Blueprint & Sign-off",
        date: "Early to Mid March 2026",
        body: "We prepared the site's structure and overall direction, then brought it back to Saudi Hayat in a dedicated review meeting to confirm everything before moving into execution.",
      },
      {
        step: "Execution, in Lockstep",
        date: "Mid to Late March 2026",
        body: "We built the site phase by phase, in continuous alignment with Saudi Hayat throughout. After every phase, we held a review session with them. Nothing moved forward without their green light.",
      },
      {
        step: "Launch",
        date: "End of March 2026",
        body: "The site went live: built around their portfolio and services, with SEO foundations already in place, ready to be found from day one, not months later.",
      },
      {
        step: "Ongoing Care",
        date: "End of March 2026 to Present",
        body: "Launch wasn't the finish line. We stayed in the backend, proactively checking that everything kept working, whether they asked us to or not. When they flagged something, we moved on it immediately.",
      },
    ],
  },
  {
    slug: "fanous-clinic",
    title: "Fanous Clinic",
    category: "Website Development",
    client: "Fanous Clinic",
    year: "2025",
    url: "https://www.fanousclinic.com",
    noEmbed: true,
    description: "A patient-first clinic website with local SEO that moved them from invisible to first-page Google results.",
    preview: "/uploads/fanous-clinic-screen.webp",
    previewMobile: "/uploads/fanous-clinic-mobile.webp",
    problemHeading: "A specialist clinic was losing patients to competitors despite offering superior medical care.",
    problemBody: "Fanous Clinic's doctors were among the most qualified in their specialty, but their website was outdated, had no online booking, and wasn't appearing in local search results. Patients actively searching for their specialty were finding competitors first.",
    solutionHeading: "We rebuilt their digital presence with patient-first design and a local SEO strategy that put them on the first page of Google.",
    solutionBody: "We redesigned the website with streamlined online booking, detailed doctor profiles, and service pages optimized for high-intent local searches. Within three months, appointment bookings increased 75%, with a 40% reduction in phone inquiries as patients began self-serving online.",
    image1: "/uploads/fanous-clinic-1.webp",
    image2: "/uploads/fanous-clinic-2.webp",
    gallery: [
      "/uploads/fanous-clinic-3.webp",
      "/uploads/fanous-clinic-4.webp",
      "/uploads/fanous-clinic-5.webp",
    ],
    results: [
      { metric: "75%", detail: "Increase in appointment bookings" },
      { metric: "40%", detail: "Reduction in phone inquiries" },
      { metric: "Page 1", detail: "Google ranking for local searches" },
    ],
  },
  {
    slug: "initio",
    title: "Initio",
    category: "Website Development",
    client: "Initio",
    year: "2026",
    url: "https://www.initio.sa",
    description: "An enterprise-grade web presence for a software startup that helped close a funding round and land two enterprise contracts.",
    preview: "/uploads/initio-screen.webp",
    problemHeading: "An enterprise software startup had a world-class product but a website that made them look like a side project.",
    problemBody: "Initio's platform solved a real enterprise problem, but their website communicated none of that credibility. Investors, potential enterprise clients, and technical hires all landed on a basic landing page that failed to convey the depth of the product or the quality of the founding team.",
    solutionHeading: "We built an enterprise-grade web presence that matched the sophistication of their actual product.",
    solutionBody: "We designed a product-led website with clear use-case positioning, an interactive demo flow, and investor-ready trust signals. The new site played a key role in closing their next funding round and landing two enterprise contracts within 60 days of launch.",
    image1: "/uploads/initio-1.webp",
    image2: "/uploads/initio-2.webp",
    gallery: [
      "/uploads/initio-3.webp",
      "/uploads/initio-4.webp",
      "/uploads/initio-5.webp",
    ],
    results: [
      { metric: "1", detail: "Funding round closed with new site" },
      { metric: "2", detail: "Enterprise contracts landed in 60 days" },
      { metric: "100%", detail: "Credibility gap eliminated" },
    ],
  },
  {
    slug: "redbone-gym",
    title: "RedBone Gym",
    category: "Website Development",
    client: "RedBone Gym",
    year: "2026",
    url: "https://www.redbonegym.com",
    description: "RedBone Gym needed a website that could handle subscriptions, service bookings, and their mobile app, fast. VELIQ delivered the complete site in seven days.",
    preview: "/uploads/redbone-gym-screen.webp",
    problemHeading: "RedBone Gym had the offer. They didn't have the time.",
    problemBody: "RedBone Gym runs a full membership business: tiered subscription plans, individually bookable services (medical consultations, cupping and massage, InBody analysis, kickboxing), and a companion mobile app. None of that had a proper home online, and there wasn't room for a long build. They needed a site that could handle real subscriptions and bookings, delivered fast, without cutting corners on scope.",
    solutionHeading: "We built the whole thing: subscriptions, bookings, and all, in seven days.",
    solutionBody: "VELIQ designed and built RedBone Gym's complete website in a single week: four subscription tiers with pricing (1, 3, 6, and 12 months), a full activities and services booking flow covering medical consultations, recovery treatments, InBody analysis, and classes, and a home for their iOS/Android app. Nothing was cut to hit the timeline. The full scope shipped on schedule.",
    image1: "/uploads/redbone-gym-1.webp",
    image2: "/uploads/redbone-gym-2.webp",
    gallery: [
      "/uploads/redbone-gym-3.webp",
      "/uploads/redbone-gym-4.webp",
      "/uploads/redbone-gym-5.webp",
    ],
    results: [
      { metric: "7 Days", detail: "From kickoff to live site" },
      { metric: "4 Tiers", detail: "Subscription plans, priced and ready to sell" },
      { metric: "5+ Services", detail: "Bookable online: medical, recovery, analysis and classes" },
    ],
    journey: [
      {
        step: "Discovery",
        date: "Day 1",
        body: "We started with a discovery meeting to understand RedBone Gym's full offering: subscription tiers, bookable services, and their existing app, and exactly what the site needed to handle from day one.",
      },
      {
        step: "Blueprint & Sign-off",
        date: "Day 1 to 2",
        body: "We moved straight into structuring the site: pricing tiers, booking flows, service pages, and confirmed the direction with RedBone Gym before execution, without slowing the pace down.",
      },
      {
        step: "Execution, in Lockstep",
        date: "Day 2 to 6",
        body: "We built the site in tight, fast cycles, staying in continuous alignment with RedBone Gym throughout. Even at this pace, nothing shipped without their review and green light.",
      },
      {
        step: "Launch",
        date: "Day 7",
        body: "The site went live: subscriptions, service bookings, and the app all in one place, one week after the first conversation.",
      },
      {
        step: "Ongoing Care",
        date: "Since Launch",
        body: "We stayed in the backend, proactively checking that everything kept working, whether they asked us to or not. When they flagged something, we moved on it immediately.",
      },
    ],
  },
  {
    slug: "captain-maged",
    title: "Captain Maged",
    category: "Website Development",
    client: "Capt. Maged",
    year: "2024",
    url: "https://captainmagedcm.com",
    description: "A personal brand platform for a maritime captain that drove a 240% increase in bookings, with a shift toward high-ticket corporate clients.",
    preview: "/uploads/captain-maged-screen.webp",
    problemHeading: "A licensed maritime captain with 20 years of experience had no way to attract and vet high-value clients online.",
    problemBody: "Captain Maged relied entirely on word-of-mouth referrals for his private sea tours and diving charters. Without a professional web presence, he couldn't reach international travelers or corporate groups willing to pay premium rates.",
    solutionHeading: "We built a personal brand platform that positioned him as the authority on private maritime experiences in the Red Sea.",
    solutionBody: "We created a professional booking website with credentials showcase, multilingual support, and a seamless reservation system. His bookings increased 240% in the first season, with a significant shift toward higher-ticket corporate clients.",
    image1: "/uploads/captain-maged-1.webp",
    image2: "/uploads/captain-maged-2.webp",
    gallery: [
      "/uploads/captain-maged-3.webp",
      "/uploads/captain-maged-4.webp",
      "/uploads/captain-maged-5.webp",
    ],
    results: [
      { metric: "240%", detail: "Increase in bookings in first season" },
      { metric: "Corporate", detail: "Shift toward high-ticket corporate clients" },
      { metric: "Global", detail: "Reach expanded to international travelers" },
    ],
  },
  {
    slug: "coach-batool",
    title: "Coach Batool",
    category: "Website Development",
    client: "Coach Batool",
    year: "2026",
    url: "https://www.coachbatool.com",
    description: "Coach Batool built a following of more than 400,000 on Instagram but had no website. VELIQ built the site and the transaction infrastructure behind it.",
    preview: "/uploads/coach-batool-screen.webp",
    problemHeading: "Coach Batool had the audience. She didn't have the infrastructure.",
    problemBody: "With more than 400,000 followers on Instagram, visibility was never the issue for Coach Batool. But she had no website at all: no way to sell her coaching packages, consultations, recipe books, or courses directly, and no system to capture or track the transactions her following was ready to make. Her reach was scaling in public, with nothing behind it to turn that attention into a trackable, sellable business.",
    solutionHeading: "We didn't build her an audience. She already had one. We built the experience and the infrastructure to convert it.",
    solutionBody: "VELIQ designed and built Coach Batool's entire website from scratch, with UX as a central focus throughout: how a visitor moves from discovering her content to purchasing a coaching package, a digital recipe book, or a course had to feel effortless. Behind that experience, we built the transaction infrastructure itself. Every purchase across her packages, consultations, and products is now captured and trackable, instead of scattered across DMs and manual bookings.",
    image1: "/uploads/coach-batool-1.webp",
    image2: "/uploads/coach-batool-2.webp",
    gallery: [
      "/uploads/coach-batool-3.webp",
      "/uploads/coach-batool-4.webp",
      "/uploads/coach-batool-5.webp",
    ],
    results: [
      { metric: "100+", detail: "Transactions through the site" },
      { metric: "$5,000+", detail: "Revenue generated through the site" },
    ],
    journey: [
      {
        step: "Discovery",
        date: "April 2026",
        body: "We started from zero, no existing website to build on. The journey began with a discovery meeting with Coach Batool to understand her programs, her audience, and exactly what the site and checkout experience needed to do for her business.",
      },
      {
        step: "Blueprint & Sign-off",
        date: "April 2026",
        body: "We prepared the site's structure and UX direction, how visitors would move from her content to a purchase, then brought it back to Coach Batool in a dedicated review meeting to confirm everything before moving into execution.",
      },
      {
        step: "Execution, UX-First",
        date: "April to May 2026",
        body: "We built the site and its transaction flows phase by phase, with UX as the central focus throughout, in continuous alignment with Coach Batool. After every phase, we held a review session with her. Nothing moved forward without her green light.",
      },
      {
        step: "Launch",
        date: "June 2026",
        body: "The site went live: built around her programs and products, with the transaction infrastructure in place from day one so every sale could be captured and tracked.",
      },
      {
        step: "Ongoing Care",
        date: "June 2026 to Present",
        body: "Launch wasn't the finish line. We stayed in the backend, proactively checking that everything kept working, whether she asked us to or not. When she flagged something, we moved on it immediately.",
      },
    ],
  },
  {
    slug: "coach-shiko",
    title: "Coach Shiko",
    category: "Website Development",
    client: "Coach Shiko",
    year: "2026",
    url: "https://www.coachmohamedroshdy.com",
    description: "Turning a 1M-follower audience into a tracked revenue engine — with the website and backend infrastructure to capture every transaction.",
    preview: "/uploads/coach-shiko-screen.webp",
    problemHeading: "Coach Shiko had the audience. He didn\u2019t have the infrastructure.",
    problemBody: "With almost 1 million followers on Instagram and a highly active presence across social media, visibility was never the issue. But he had no website, no system to capture the transactions his following was generating, and no dashboard to see what was actually converting. His reach was scaling in public, with nothing behind it to turn that attention into tracked, manageable business.",
    solutionHeading: "We didn\u2019t build him an audience \u2014 he already had one. We built the infrastructure to run a business behind it.",
    solutionBody: "VELIQ designed and built Coach Shiko\u2019s website along with the backend infrastructure to capture every transaction generated through the site and route it into a single dashboard \u2014 so he can see leads, bookings, and revenue in real time, instead of guessing at what his following is actually converting into. Every phase was built in partnership with him, reviewed and approved before we moved forward, so what launched in April was exactly what he needed.",
    image1: "/uploads/coach-shiko-1.webp",
    image2: "/uploads/coach-shiko-2.webp",
    gallery: [
      "/uploads/coach-shiko-3.webp",
      "/uploads/coach-shiko-4.webp",
      "/uploads/coach-shiko-5.webp",
    ],
    results: [
      { metric: "300+", detail: "Qualified leads generated" },
      { metric: "EGP 500K+", detail: "Revenue generated through the site" },
      { metric: "200K+", detail: "Site sessions" },
    ],
    journey: [
      {
        step: "Discovery",
        date: "February 2026",
        body: "We started from zero infrastructure \u2014 no website, no way to capture or track what his large following was already generating. The journey began with a meeting with Coach Shiko to understand exactly what he needed the site and backend to do for his business: his goals, his audience, and his method.",
      },
      {
        step: "Blueprint & Sign-off",
        date: "February \u2013 March 2026",
        body: "We took the time to prepare the site\u2019s skeleton and shape the overall direction, then brought it back to him in a dedicated review meeting to confirm everything before moving into execution.",
      },
      {
        step: "Execution, in Lockstep",
        date: "March \u2013 April 2026",
        body: "We built the site phase by phase, in continuous alignment with Coach Shiko throughout. After every phase, we held a review session with him \u2014 nothing moved forward without his green light.",
      },
      {
        step: "Launch",
        date: "April 2026",
        body: "The site went live: built around his methodology, connected to the transaction infrastructure, and structured to capture and track every lead his audience sent to it.",
      },
      {
        step: "Ongoing Care",
        date: "April 2026 \u2013 Present",
        body: "Launch wasn\u2019t the finish line. We stayed in the backend, proactively checking that everything kept working \u2014 whether he asked us to or not. When he flagged something, we moved on it immediately.",
      },
    ],
  },
  {
    slug: "window-adv",
    title: "Window Adv",
    category: "SEO",
    client: "Window Adv",
    year: "2024",
    url: "https://windowadv.com",
    noEmbed: true,
    description: "A digital media platform that brought an outdoor advertising portfolio online and opened a new digital-sourced revenue channel.",
    preview: "/uploads/window-adv-screen.webp",
    previewMobile: "/uploads/window-adv-mobile.webp",
    problemHeading: "An outdoor advertising agency had no digital strategy for a business that was entirely offline.",
    problemBody: "Window Adv managed a substantial portfolio of billboards and outdoor placements but had zero digital infrastructure. There was no online portfolio, no digital inquiry system, and no way for media buyers to evaluate inventory remotely, a critical gap in an increasingly digital-first media market.",
    solutionHeading: "We built a digital media platform that brought their entire outdoor inventory online for remote evaluation and booking.",
    solutionBody: "We designed a media buyer-focused platform with an interactive location map, audience data per placement, and a streamlined campaign inquiry flow. Digital-sourced inquiries became their fastest-growing revenue channel within six months of launch.",
    image1: "/uploads/window-adv-1.webp",
    image2: "/uploads/window-adv-2.webp",
    gallery: [
      "/uploads/window-adv-3.webp",
      "/uploads/window-adv-4.webp",
      "/uploads/window-adv-5.webp",
    ],
    results: [
      { metric: "#1", detail: "Fastest-growing revenue channel" },
      { metric: "Digital", detail: "New digital-sourced inquiry pipeline" },
      { metric: "6 mo", detail: "Time to become top revenue source" },
    ],
  },
  {
    slug: "enjazcare",
    title: "Enjaz Care",
    category: "Website Development",
    client: "Enjaz Care",
    year: "2026",
    url: "https://enjazcare.sa",
    description: "A bilingual service platform for a Riyadh-based home and facility maintenance company offering booking, pricing calculators, and six integrated service categories.",
    preview: "/uploads/enjazcare-screen.webp",
    problemHeading: "A home maintenance company in Riyadh had no digital booking system and was losing clients to competitors with online presence.",
    problemBody: "Enjaz Care offered a comprehensive range of services, including pest control, deep cleaning, furniture moving, disinfection, and maintenance, but had no way for customers to discover, compare, or book services online. Inquiries came only through phone calls and WhatsApp, limiting their reach and making it impossible to scale beyond word-of-mouth referrals in a competitive Saudi market.",
    solutionHeading: "We built a bilingual service platform with online booking and a pricing calculator that turned visitors into booked appointments.",
    solutionBody: "We designed a professional Arabic-first website with English support, featuring a built-in pricing calculator, structured service pages for each category, an online booking system, and WhatsApp integration. The platform now serves residential and commercial clients across Riyadh, from homes to hospitals, factories, and hotels, with a streamlined digital experience that matches the quality of their on-site work.",
    image1: "/uploads/enjazcare-1.webp",
    image2: "/uploads/enjazcare-2.webp",
    gallery: [
      "/uploads/enjazcare-3.webp",
      "/uploads/enjazcare-4.webp",
      "/uploads/enjazcare-5.webp",
    ],
    results: [
      { metric: "6", detail: "Service categories integrated into one platform" },
      { metric: "2", detail: "Languages (Arabic-first + English)" },
      { metric: "Online", detail: "Booking system replacing phone/WhatsApp only" },
    ],
  },
  {
    slug: "crewhub-studio",
    title: "Crewhub Studio",
    category: "Website Development",
    client: "Crewhub Studio",
    year: "2026",
    url: "https://crewhubstudio.com",
    noEmbed: true,
    description: "A portfolio and booking platform for a creative production studio that turned their social following into a consistent inbound client pipeline.",
    preview: "/uploads/crewhub-studio-screen.webp",
    previewMobile: "/uploads/crewhub-studio-mobile.webp",
    problemHeading: "A creative studio with a strong portfolio and social presence had no website to convert followers into paying clients.",
    problemBody: "Crewhub Studio was producing high-quality commercial photography, videography, and creative direction, but their digital presence lived entirely on social media. Without a dedicated website, potential clients had no professional touchpoint to review their work, understand their process, or request a quote — limiting growth to referrals and DMs.",
    solutionHeading: "We built a visually immersive studio website that turns portfolio browsers into booked clients.",
    solutionBody: "We designed a dark, cinematic website that showcases their creative work across photography, video, and direction. A structured services breakdown, client inquiry form, and seamless booking flow gave Crewhub a professional home that immediately elevated their perceived value and opened doors to larger brand partnerships.",
    image1: "/uploads/crewhub-studio-1.webp",
    image2: "/uploads/crewhub-studio-2.webp",
    gallery: [
      "/uploads/crewhub-studio-3.webp",
      "/uploads/crewhub-studio-4.webp",
      "/uploads/crewhub-studio-5.webp",
    ],
    results: [
      { metric: "Day 1", detail: "Inbound brand inquiries from launch" },
      { metric: "Pro", detail: "Elevated perceived value vs. social-only presence" },
      { metric: "Booking", detail: "Structured flow replacing ad-hoc DMs" },
    ],
  },
  {
    slug: "lamat-elarabia",
    title: "Lamat El Arabia",
    category: "SEO",
    client: "Lamat El Arabia",
    year: "2026",
    url: "https://lamat-elarabia.org",
    noEmbed: true,
    description: "An SEO strategy that took an Arabic cultural brand from invisible in search to ranking for high-intent artisan and cultural product keywords.",
    preview: "/uploads/lamat-elarabia-screen.webp",
    previewMobile: "/uploads/lamat-elarabia-mobile.webp",
    problemHeading: "A cultural artisan brand with authentic products was being outranked by generic e-commerce stores with no cultural credibility.",
    problemBody: "Lamat El Arabia offered handcrafted Arabic cultural products with genuine heritage and quality, but their website wasn't appearing in search results for the keywords their customers were using. Generic competitors with larger ad budgets were capturing their natural audience, and organic traffic was near zero.",
    solutionHeading: "We built an SEO foundation that matched their cultural authority with the search visibility they deserved.",
    solutionBody: "We conducted thorough keyword research focused on high-intent Arabic cultural product queries, rebuilt their on-page structure, added structured data for products and organization, and developed a content strategy around cultural storytelling. Organic visibility grew significantly within the first few months, bringing in qualified buyers who were actively looking for authentic Arabic artisan products.",
    image1: "/uploads/lamat-elarabia-1.webp",
    image2: "/uploads/lamat-elarabia-2.webp",
    gallery: [
      "/uploads/lamat-elarabia-3.webp",
      "/uploads/lamat-elarabia-4.webp",
      "/uploads/lamat-elarabia-5.webp",
    ],
    results: [
      { metric: "Organic", detail: "Traffic growth from near-zero baseline" },
      { metric: "Page 1", detail: "Rankings for key cultural product terms" },
      { metric: "Qualified", detail: "Buyers from search replacing ad spend" },
    ],
  },
  {
    slug: "bedouin-trails",
    title: "Bedouin Trails",
    category: "SEO",
    client: "Bedouin Trails",
    year: "2026",
    url: "https://bedouintrails.com",
    noEmbed: true,
    description: "An SEO overhaul for a desert tourism operator that moved them from page 3 to the top of Google for high-value adventure travel searches.",
    preview: "/uploads/bedouin-trails-screen.webp",
    previewMobile: "/uploads/bedouin-trails-mobile.webp",
    problemHeading: "A premium desert tourism company was buried in search results while international travelers booked with inferior competitors.",
    problemBody: "Bedouin Trails offered authentic, high-quality desert experience tours for international travelers, but were effectively invisible online. Tourists searching for desert adventures and Bedouin experiences found larger aggregator platforms and competitors first — meaning Bedouin Trails was losing bookings to operators who couldn't match their authenticity or experience quality.",
    solutionHeading: "We built an SEO strategy targeting high-intent international travel searches and put Bedouin Trails on the first page.",
    solutionBody: "We restructured their site architecture around destination and experience-specific landing pages, implemented schema markup for tours and local business, and built a content strategy targeting long-tail adventure travel queries. The result was a significant jump in organic rankings for their core booking terms, driving qualified international traffic directly to their booking flow.",
    image1: "/uploads/bedouin-trails-1.webp",
    image2: "/uploads/bedouin-trails-2.webp",
    gallery: [
      "/uploads/bedouin-trails-3.webp",
      "/uploads/bedouin-trails-4.webp",
      "/uploads/bedouin-trails-5.webp",
    ],
    results: [
      { metric: "3x", detail: "Organic traffic growth within 4 months" },
      { metric: "15+", detail: "Keywords ranking on page 1 of Google" },
      { metric: "0%", detail: "Aggregator commission — all bookings direct" },
    ],
  },
  {
    slug: "brandlab",
    title: "Brandlab",
    category: "Website Development",
    client: "Brandlab",
    year: "2026",
    url: "https://www.brandlabagency.co",
    description: "Brandlab creates polished video content for fitness brands, life coaches, and startups worldwide but had no website of their own. VELIQ built the site from scratch with UX as the core focus, then layered in SEO a month after launch.",
    preview: "/uploads/brandlab-screen.webp",
    problemHeading: "Brandlab made other brands look incredible. Their own brand had no website at all.",
    problemBody: "Brandlab edits video, motion graphics, and content for startups, freelancers, and creators, with a strong base of clients in the fitness and life-coaching space. But despite a portfolio built on making other people's brands look sharp, they had no website of their own: no way for a prospective client to see their work, understand their services, or book a call without going through social media or word of mouth first.",
    solutionHeading: "We built their site from scratch, and made UX the whole point.",
    solutionBody: "VELIQ designed and built Brandlab's entire website from the ground up. Because Brandlab's business is built on how things look and feel, the build was UX-first from day one: every page, showcase, and interaction was designed around how a visitor actually experiences the site, not just how it looks in a screenshot. SEO came a month after launch, as a deliberate second phase, not a same-day afterthought.",
    image1: "/uploads/brandlab-1.webp",
    image2: "/uploads/brandlab-2.webp",
    gallery: [
      "/uploads/brandlab-3.webp",
      "/uploads/brandlab-4.webp",
      "/uploads/brandlab-5.webp",
    ],
    results: [
      { metric: "326", detail: "Search impressions on Google" },
      { metric: "12", detail: "Organic clicks to the site" },
      { metric: "25.3", detail: "Average search position, early-stage" },
    ],
    journey: [
      {
        step: "Discovery",
        date: "Early May 2026",
        body: "We started from zero, no existing website to build on. The journey began with a discovery meeting with Brandlab to understand their services, their clients, and exactly what the site needed to do for them.",
      },
      {
        step: "Blueprint & Sign-off",
        date: "Early to Mid May 2026",
        body: "We prepared the site's structure and UX direction, then brought it back to Brandlab in a dedicated review meeting to confirm everything before moving into execution.",
      },
      {
        step: "Execution, UX-First",
        date: "Mid to Late May 2026",
        body: "We built the site phase by phase, with UX as the central focus throughout. How the site felt to move through mattered as much as how it looked. After every phase, we held a review session with Brandlab. Nothing moved forward without their green light.",
      },
      {
        step: "Launch",
        date: "June 2026",
        body: "The site went live: a cinematic, bilingual (Arabic/English) home for Brandlab's work, built around their portfolio and services.",
      },
      {
        step: "SEO Initialization",
        date: "July 2026",
        body: "A month after launch, we began a dedicated SEO initialization phase, building the technical and content foundations for organic search on top of the UX work already in place.",
      },
      {
        step: "Ongoing Care",
        date: "July 2026 to Present",
        body: "We stayed in the backend, proactively checking that everything kept working, whether they asked us to or not. When they flagged something, we moved on it immediately.",
      },
    ],
  },
];

export function getProject(slug: string): Project | undefined {
  return PROJECTS.find((p) => p.slug === slug);
}

export function getOtherProjects(slug: string, count = 4): Project[] {
  const start = PROJECTS.findIndex((p) => p.slug === slug);
  const ordered = [...PROJECTS.slice(start + 1), ...PROJECTS.slice(0, start + 1)];
  return ordered.filter((p) => p.slug !== slug).slice(0, count);
}
